version: '3'
services:
    grubapi:
      container_name: grubapi
      restart: always
      build:
          dockerfile: Dockerfile
          context: ./grubapi
      ports:
        - '3333:3333'
    grubui-dev:
      tty: true
      container_name: grubui-dev
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./grubui
      volumes:
        - '/app/node_modules'
      ports:
        - '3000:3000'
      environment:
        - CHOKIDAR_USEPOLLING=true