version: '3'
services:
    grubapi:
      container_name: grubapi
      restart: always
      build:
          dockerfile: Dockerfile
          context: ./grubapi
      ports:
        - '3333:3333'
    grubui-prod:
      container_name: grubui-prod
      restart: always
      build:
        dockerfile: Dockerfile.prod
        context: ./grubui
      ports:
        - '1337:80'