name: grub

on:
  push:
    branches:
    - main
    - staging
    - develop
  pull_request:
    branches:
    - main
    - staging
    - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0' # The Go version to download (if necessary) and use.
    
    # Setup Node
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
          node-version: '12'
    
    # Make .env file
    - name: Make .env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_ATLAS_URI: ${{ secrets.ATLAS_URI }}
        envkey_DB_NAME: ${{ secrets.DB_NAME }}
        file_name: .env

    # Run testing on the code
    - name: Run testing
      run: |
        ls
        cd grubapi
        go test -v
